<?php
//=============================================================================
//
// File:         /i18n/haFavor.inc
//
// Language:     PHP
//
// Contents:     ha = Harshen Hausa
//
// Author:       Joe Honton © 2014
//
// Initial date: January 18, 2014
//
//=============================================================================

require_once( __DIR__ . '/haBasePage.inc' );


//-------------------------------------
class haFavor extends haBasePage
{
	//---------------------------------
	function __construct( $language, $pagename )
	{
		parent::__construct( $language, $pagename );
	}
	
	//=============================================================================
	// Standard <head> items
	//=============================================================================
	
	//---------------------------------
	function pageTitle()
	{
		return "Ina da bukatar";
	}
	
	//---------------------------------
	function metaDescription()
	{
		return "Za ka iya taimaka da magana da ƙarfin hali game da hatsarori da makaman nukiliya fission.";
	}
	
	//---------------------------------
	function metaKeywords()
	{
		return "nukiliya da wurin, makaman nukiliya da iko, nukiliya makamashi, makaman nukiliya, fission, duniya, daga ruwan zãfi, da wutar lantarki";
	}
	
	//=============================================================================
	// Earth
	//=============================================================================
	
	//---------------------------------
	function blueMarble()
	{
		return "mu kyau shudi marmara!";
	}
	
	//=============================================================================
	// Buttons
	//=============================================================================
	
	//---------------------------------
	function pledgeButton()
	{
		return "rantsuwarsu yi alkawari";
	}
	
	//---------------------------------
	function pledgeButtonAlt()
	{
		return 'Ku yi rantsuwa da "ba tare da nukiliya fission" rantsuwa a yanzu';
	}

	//=============================================================================
	// Content
	//=============================================================================
	
	//---------------------------------
	function content()
	{
return <<<ENDHTML
			<h1>Za ka iya taimaka da magana da ƙarfin hali</h1>
			
			<p>Sannu,</p>
			
			<p>Ina da bukatar. <strong>Za a iya taya ni a yawon ganin kwaf don yin wannan a duniya ba tare da nukiliya fission?</strong></p>
			
			<p>Bari in bayyana dalilin da ya sa ban ji haka karfi game da wannan.</p>
	
			<p>Lokacin da na fara girma, shi ne bincike sararin samaniya a tsawo ta cika girma. A tashin hankali da cewa tare da kasada alama da za a raba da kowa. A tashin hankali tare da kowane sabon yi, Ya sa mu so ƙarin. Kuma jira ne da muke gaske sun je saka mutum a kan wata a mayar da shi zuwa ga duniya lafiya, kiyaye mu shiga tare da har ma da qananan succès da kasawa wannan aiki.</p>
			
			<p>Kafin kai da matuƙar manufa, akwai mutane da yawa da muhimmanci nasarori. Daya daga cikin mafi ban sha'awa daga cikin waɗannan da aka lokacin da astronauts karya daga duniya kewayewa. A karo na farko, mutane suna barin aminci su gida duniya. Mun yi kamar mai kasada neman a kan kasada wata rayuwa.</p>
			
			<p>Kuma a sa'an nan ya fi na ƙwarai abu da ya faru. A astronauts duba baya a duniya, kuma ya ga na farko da blue marmara da cewa shi ne mu na gida, da kuma kusan an shere da daraja kyau ga abin da suke duba. A hotunan da suka aiko da baya da aka watsa shirye-shirye ga duniya, kuma ba mu ma su na cikin tsõro.</p>
			
			<p>A yanayin shigewa kama a wadanda hotunan Ya sa mu san kanmu a hanyar da transcended dukkan harkokin siyasa. Bayan ɗan lokaci, a lokacin, mun manta game da Cacar Baki, muna ajiye dake tsakaninmu, kuma ba mu mamakin da kyau na duniya. Daga wannan sabon sani mun san yadda aras mu wuri a cikin duniya shi ne, da kuma yadda sosai a kusa mun kasance, ga lalata gida ne kawai za mu taba samun.</p>
			
			<p>Za mu tada hankali da na gaggawa zuwa ga gyara da shortcomings. Tare da fashe da aiki, za mu yi aiki zuwa ga gyara da matsaloli. A ƙasashen duniya yarjejeniya a kan makaman nukiliya yaduwa, da kuma yarjejeniya don ban duk a sama-ƙasa gwajin makaman nukiliya da aka tabbatar da cewa za mu iya magana a kan martabobi da mu raba na kowa cimma burin m. A ƙarshe, daga faɗuwar da bangon Berlin, da kuma thawing na dangantaka tsakanin babba hammayarsu Cacar Baki, muka fara na farko mai tsanani kokarin nufin rage a duniya jari na makaman nukiliya.</p>
			
			<p>Amma tun wannan lokacin da muka ze yi hasãrar mu fervor a duniya daga makaman nukiliya, kuma kwanan nan, kokarin ci gaba da cewa aikin da ba ya da yawa hakikanin ci gaba. Bayan shekaru hudu na tattaunawa mai rauni, mun kasance ba ma iya kula da na yanzu na harkokin: duniya makaman nukiliya yarjejeniyar da aka yi watsi; da tsufa a duniya makamai masu linzami ba mai lafiya; da kuma sababbin makaman nukiliya ya ci gaba da bincike.</p>
			
			<p><strong>Da manufar a fili ya hallaka kasa.</strong> Tare da kunya, an maye gurbinsu m alkawuran da wofi kalmomi.</p>
			
			<p>Abin ba in ciki, makaman nukiliya ba mu damu ne kawai. Yanzu mun san cewa makaman nukiliya da iko tsire-tsire kuma shirya kai barazana ga daraja duniya. Muna kawai fara tada zuwa ganin cewa makaman nukiliya da iko tsire-tsire ba za a iya sanya 100% hadari.</p>
			
			<p>A masifa a Fukushima taba kamata ya faru saboda makaman nukiliya injiniyoyi sun shirya kowane yiwu m-harka labari: suna da aminci dokoki a wurin kowane yanki na kayan aiki; aiki hanyoyin da kowane mai yiwuwa halin da ake ciki. gaggawa na shirye-shiryenku na lokacin da abubuwa suka tafi daidai ba; kuma mahara na atomatik idan sunadaran da ajiye kayan aiki bai yi aiki. Dukkanin masana'antu da injiniyoyi mafi kyau suna aiki a hankali tare da kare lafiya kamar yadda su fi mayar da hankali. Amma duk da haka har yanzu wani abu mai tsanani ya faru. Kuma ka ambaci, wannan ya faru shekaru 25, bayan ta cherno, tare da isasshe lokaci zuwa koya daga baya kuskure.</p>
			
			<p>Wadannan kwanaki Ina da wuya mũmina lokaci kusan kome da cewa makaman nukiliya makamashi da kamfanoni gaya mani. Mai rahusa fiye da zabi? Abin tsabtata fiye da zabi? Mafi aminci fiye da zabi? A'a. A'a. A'a.</p>
			
			<p><strong>Duk wannan kawai don tafasa ruwa?</strong></p>
	
			<p>A nan ne mai sauki gaskiya babu wani abu na musamman game da wutar lantarki halitta makaman nukiliya ikon shuke-shuke. Shafa da mai, ci, iskar gas, da kuma makaman nukiliya duk yi amfani da wannan domin samar da wutar lantarki makanikai. Yana da sauki ne:</p>
			
			<ol>
				<li>A zafi masomi tafasa da ruwa.</li>
				<li>Tururi daga ruwan zãfi sojojin ruwan wukake zuwa injin turbin juya.</li>
				<li>Gudanar da waya a haɗe zuwa kadi inji mai farfela haifar da wutar lantarki a lokacin da ta juya su magnetic filin.</li>
			</ol>
			
			<p>Sa wutar lantarki mai adalci ne mai sauki watsi da kimiyya da aikin injiniya. To, me ya sa je matsala, daga ruwan zãfi by tsagawa hargitsatstsun kwayoyin halitta? Me ya sa halitta masu kawo hadari makaman nukiliya sharar gida ne da muke ba zai taba rabu da mu? Me ya sa ganimar yanayi tare da uranium hakan ma'adinai da tsaftacewa cewa halitta mai guba sharar gida-asashe? Kuma me ya sa makaman nukiliya ikon kamfanonin aikawa da wannan fasaha kawo hadari ga kasashe masu tasowa?</p>
			
			<p>Saboda haka a nan shi ne bukata. <strong>Za a iya taya ni magana game da waɗannan abubuwan gaskiya m?</strong> Ni ba zan tambayar ka ka shiga wata ƙungiyar ko don donate kudi, amma kawai don ƙara Sunan ka ga jerin m mutane da suka yi zai yi magana a cikin ni'imar a duniya, ba tare da makaman nukiliya fission.</p>
			
			<p>Ina fatan wannan zai sa wani bambanci.</p>
			
			<p>Joseph Honton<br />
			Sebastopol, California, USA</p>
ENDHTML;
	}
}
?>