<?php
//=============================================================================
//
// File:         /i18n/jvFavor.inc
//
// Language:     PHP
//
// Contents:     jv = Basa Jawa (Javanese)
//
// Author:       Joe Honton © 2013
//
// Initial date: October 13, 2013
//
//=============================================================================

require_once( __DIR__ . '/jvBasePage.inc' );


//-------------------------------------
class jvFavor extends jvBasePage
{
	//---------------------------------
	function __construct( $language, $pagename )
	{
		parent::__construct( $language, $pagename );
	}
	
	//=============================================================================
	// Standard <head> items
	//=============================================================================
	
	//---------------------------------
	function pageTitle()
	{
		return "Kudu panyuwunan";
	}
	
	//---------------------------------
	function metaDescription()
	{
		return "Panjenengan saged kanthi lisan banter bab beboyo saka nuklir fission.";
	}
	
	//---------------------------------
	function metaKeywords()
	{
		return "nuklir fasilitas, nuklir daya, energi nuklir, senjata nuklir, fission, Bumi, nggodhok banyu, listrik";
	}
	
	//=============================================================================
	// Earth
	//=============================================================================
	
	//---------------------------------
	function blueMarble()
	{
		return "kita ayu biru neker!";
	}
	
	//=============================================================================
	// Buttons
	//=============================================================================
	
	//---------------------------------
	function pledgeButton()
	{
		return "Manahil janji";
	}
	
	//---------------------------------
	function pledgeButtonAlt()
	{
		return 'Sumpah sing "ora liyane fission" sumpah saiki!';
	}

	//=============================================================================
	// Content
	//=============================================================================
	
	//---------------------------------
	function content()
	{		 		 
return <<<ENDHTML
			<h1>Panjenengan saged kanthi lisan karo wani</h1>
			
			<p>Halo,</p>
			
			<p>Kudu panyuwunan. <strong>Kula sampeyan bantuan kula sandi ing nggoleki kanggo nggawe iki menyang Janapada tanpa nuklir fission? </strong></p>
			
			<p>Ngidini kula kanggo nerangake apa aku rase supaya banget bab iki.</p>
	
			<p>Nalika aku iki akeh serep, papan njelajahi pilihan ana ing dhuwur saka sawijining kebak kamulyan. Ing kasenengan sing diiringi ngulandara ketoke dienggo bareng dening saben siji. Ing sensai sing diiringi saben acara anyar, diwanti-wanti kita liyane. Lan nunggu kita saestu padha arep sijine wong ing rembulan lan bali marang aman Bumi, katahan kita tunangan karo malah suntingan kasile lan gagal saka proyek.</p>
			
			<p>Sadurunge sik njongko sing goal pokok, ana akeh penting prestasi. Salah siji sing paling macem kasebut ana nalika astronauts nyuwil adoh saka Bumi gravitasi. Pisanan, manungsa padha nilaraken safety sing planet ngarep. Kita padha kaya wong golek sensai ing ngulandara saka umur.</p>
			
			<p>Lan banjur ingkang paling apik banget kedaden. Ing astronauts kapandeng bali ing bumi receding, lan weruh pisanan ing neker biru sing ana ngarep kita, lan padha saklawasé kepunjulen dening kaendahan larang regane apa padha weruh. Gambar-gambar foto sing padha pesen dikirim maneh padha dikirim menyang donya, lan kita padha seneng banget.</p>
			
			<p>Ing kerentanan dijupuk sing digawe foto kita sadar saka kangge kita sesambetan ing cara sing dibusak kabeh politik. Kanggo wayahe ing wektu cendhak, kita kelalen bab Perang Kadhemen, kita cawisaken kita beda, lan kita marveled ing kaendahan saka Bumi. Saka eling anyar kita sumurup mung carane pecah kita panggonan ing universe iki, lan carane banget banget nutup kita padha kanggo ngancurake ing ngarep mung kita tau duwe.</p>
			
			<p>We diwiwiti karo pangertèn saka kacepetan kanggo ndandani masalah kita. Kanthi bledosan aktivitas, kita makarya kanggo ndandani masalah kita. Ing kasepakatan internasional senjata nuklir tambahan, lan persetujuan kanggo Ban testing kabeh ndhuwur-lemah saka nuklir senjata padha bukti sing bisa pirembagan bab kita sambungan angka lan entuk umum gol nyoto. Pungkasanipun, karo tiba ing Tembok Berlin, lan thawing saka hubungan antarane musuh utama Perang Kadhemen, kita wiwit ing kawitan serius gaweyan ngarahke ing ngurangi ing keluwihan global nuklir senjata.</p>
			
			<p>Nanging wiwit wektu kita koyone wis ilang kita fervor kanggo janapada tanpa senjata nuklir, lan karya anyar terus karya sing wis ora digawe luwih nyata proses. Sawise patang puluh kang banget wuwus, kita malah wis bisa kanggo njaga negara sing saiki urusane: internasional nuklir treaties wis digathekno; sing tuwa global keluwihan sing bejat mudhun; anyar lan gaman nuklir riset terus.</p>
			
			<p><strong>Kabijakan saka ajerih perang wis cetha gagal.</strong> Kanggo kita kawirangan, iku wis diganti dening samar lan prajanji nggambarake owahan retorika.</p>
			
			<p>Susah, gaman nuklir ora kita mung badhan. Saben uwong saiki sing mangerténi nuklir daya tetanduran uga nuduhke a ancaman serius kita larang regane Bumi. Saben uwong mung kanggo wiwit tangi menyang jaminan sing nuklir daya tetanduran ora bisa digawe 100% aman.</p>
			
			<p>Ing bilai elek ing Fukushima tau ngirim wis kedaden amarga engineers nuklir wis disiapake kanggo saben bisa paling awon cilik skenario: padha aman aturan ing panggonan kanggo saben bagean peralatan; operasi cara kanggo saben kahanan bisa; mungkin plans nalika iku yen salah; lan sawetara mekanisme otomatis ing huruf gedhe-cilik peralatan cadangan durung bisa. Kabeh industri paling apik engineers padha digunakake kanthi teliti karo aman minangka sing paling prioritas. Nanging isih soko elek kedaden. Lan-eling, iki wonten 25 taun sawise Chernobyl, karo akeh wektu kanggo sinau saka sadurungé kesalahane.</p>
			
			<p>Dina iki aku duwe wektu banget angel pracaya meh tindakan yen energi nuklir perusahaan ngomong. Luwih murah tinimbang wong liyane? Luwih resik tinimbang wong liyane? Luwih aman tinimbang wong liyane? Boten. Boten. Boten.</p>
			
			<p><strong>Kabeh iki mung kanggo godhok banyu?</strong></p>
	
			<p>Punika bebener sing prasaja: ana apa-apa khusus babagan listrik kui dening nuklir tetanduran daya. Oil, batu bara, gas, lan nuklir kabeh nggunakake kawruh babagan mesin padha kanggo ngasilaken listrik. Iku prasaja:</p>
			
			<ol>
				<li>A sumber panas ndadekake banyu panas.</li>
				<li>Uap saka banyu panas pasukan turbin glathi kanggo muter.</li>
				<li>Prabawa gulungan kawat ditempelake menyang turbin obah nggawe listrik nalika diputer liwat kolom magnetik.</li>
			</ol>
			
			<p>Ngasilaken listrik namung pokok fisika lan engineering. Supaya apa menyang alangan saka nggodhok banyu dening pisah atom? Apa nggawe mbebayani sampah nuklir sing bisa tau njaluk nyisihaken apa? Apa rusaking lingkungan karo uranium pertambangan lan panggilingan sing nggawe beracun sampah-bantala? Lan apa sing nuklir daya perusahaan ngekspor teknologi iki mbebayani kanggo ngembangaké negara?</p>
			
			<p>Supaya punika request. <strong>bisa sampeyan kula bantuan kanggo pirembagan babagan iki bukti prasaja?</strong> Aku ora takon sampeyan melu organisasi utawa kanggo nyumbang dhuwit, nanging mung kanggo nambah jeneng kanggo dhaptar wani sopo sing bakal nganggo ing sih saka janapada tanpa nuklir fission.</p>
			
			<p>Mugi iki bakal nggawe prabédan karo.</p>
			
			<p>Joseph Honton<br />
			Sebastopol, California, USA</p>
ENDHTML;
	}
}
?>