<?php
//=============================================================================
//
// File:         /i18n/eoFavor.inc
//
// Language:     PHP
//
// Contents:     eo = Esperanto
//
// Author:       Joe Honton © 2013
//
// Initial date: December 28, 2013
//
//=============================================================================

require_once( __DIR__ . '/eoBasePage.inc' );


//-------------------------------------
class eoFavor extends eoBasePage
{
	//---------------------------------
	function __construct( $language, $pagename )
	{
		parent::__construct( $language, $pagename );
	}
	
	//=============================================================================
	// Standard <head> items
	//=============================================================================
	
	//---------------------------------
	function pageTitle()
	{
		return "Mi havas peton";
	}
	
	//---------------------------------
	function metaDescription()
	{
		return "Vi povas helpi parolante kuraĝe pri la danĝeroj de nuklea fisio.";
	}
	
	//---------------------------------
	function metaKeywords()
	{
		return "nukleaj instalaĵoj, nuklea energio, la nukleaj armiloj, la fisio, Tero, bolanta akvo, elektro";
	}
	
	//=============================================================================
	// Earth
	//=============================================================================
	
	//---------------------------------
	function blueMarble()
	{
		return "nia bela blua marmoro!";
	}
	
	//=============================================================================
	// Buttons
	//=============================================================================
	
	//---------------------------------
	function pledgeButton()
	{
		return "solene promesi";
	}
	
	//---------------------------------
	function pledgeButtonAlt()
	{
		return 'Ĵuru al la "ne plu fisio" ĵuro nun!';
	}

	//=============================================================================
	// Content
	//=============================================================================
	
	//---------------------------------
	function content()
	{
return <<<ENDHTML
			<h1>Vi povas helpi parolante kuraĝe</h1>
			
			<p>Saluton,</p>
			
			<p>Mi havas peton. <strong>Ĉu vi povas helpi min en mia serĉo por fari ĉi tiun mondon sen nukleaj fisio?</strong></p>
			
			<p>Permesu al mi ekspliki kial mi sentas tiom forte pri tio.</p>
	
			<p>Kiam mi kreskis, kosma esplorado estis ĉe la alteco de ĝia plena gloro. La ekscitiĝo kiu akompanis la aventuro ŝajnis esti dividita de ĉiuj. La emocio kiu akompanis ĉiu nova mejloŝtono, akrigis niaj apetitoj pli. Kaj la atendo, ke ni vere volus meti homon sur la lunon kaj revenas lin sekure al la Tero, malhelpis al ni kontraktitaj kun eĉ la plej malgrandaj sukcesoj kaj fiaskoj de la projekto.</p>
			
			<p>Antaŭ atingi tiun finan celon, estis multaj gravaj atingoj. Unu el la plej exhilarating el tiuj estis kiam la astronaŭtoj rompis libera de tera orbito. Por la unua fojo, la homoj lasis la sekureco de sia hejmo planedo. Ni estis kiel emocii serĉantoj pri la aventuro de la tuta vivo.</p>
			
			<p>Kaj tiam la plej rimarkinda afero okazis. La astronaŭtoj ekrigardis ree en la malproksimigas la Tero, kaj vidis la unuan fojon la blua marmoro kiu estis nia hejmo, kaj ili estis preskaux premitaj de la altvaloraj beleco de kion ili vidis. La fotografia bildojn kiujn ili sendis returne estis transdonita al la mondo, kaj ankaŭ ni estis imponis.</p>
			
			<p>La vundebleco kaptita en tiuj fotoj faritaj al ni konscias nian en maniero kiu superis cxiujn politiko. Por mallonga momento en tempo, ni forgesis pri la Malvarma Milito, ni metis flanken niajn diferencojn, kaj ni miris pri la beleco de la Tero. De tiu nova konscio ni sciis precize kiel fragila nia loko en la universo estis, kiom danĝere proksimaj ni devis detrui la sola hejme ni iam havos.</p>
			
			<p>Ni vekiĝis kun sento de urĝeco ripari niajn mankojn. Kun ráfaga de aktiveco, ni laboris por fiksi niajn problemojn. La internacia traktato pri nuklea armiloj proliferación, kaj la interkonsento malpermesi cxiujn supre-tero testado de nukleaj armiloj estis pruvo, ke ni povus paroli pri niajn komunajn valorojn kaj atingi komunajn saĝa celojn. Eventuale, kun la falo de la Berlina Muro, kaj la thawing de rilatoj inter la ĉefaj rivaloj de la Malvarma Milito, ni komencis la unuan seriozan penado celas redukti la tutmonda malpermesas stoki de nukleaj armiloj.</p>
			
			<p>Sed ekde tiu tempo ni ŝajnas esti perdita nia fervoro por mondo libera de nukleaj armiloj, kaj la lastaj klopodoj por daŭrigi tiun laboron ja ne faris realan progreson. Post kvar jardekoj da pala prelegoj, ni eĉ ne povis subteni la nunan staton de la aferoj: la internacia nuklea traktatoj estis ĉirkaŭiri aŭ ignoritaj: la maljuniĝanta tutmondaj rezervoj estas difektita; kaj novaj atomarmiloj esploro daŭras.</p>
			
			<p><strong>La politiko de deterrence klare malsukcesis.</strong> Por nia abomenindaĵo, ĝi estis anstataŭita de pigraj promesoj kaj malplena retoriko.</p>
			
			<p>Malfelicxe, la nukleaj armiloj ne estas nia sola zorgo. Ni nun scias ke nuklea energio ankaŭ proponas seriozan minacon al nia grandvalora Tero. Ni ĵus komencis vekiĝi al la konstato, ke la nuklea energio ne povas esti farita 100% sekura.</p>
			
			<p>La katastrofo en Fukushima neniam devus esti okazinta pro la nukleaj inĝenieroj estis pretigita por cxiu ebla malbona-kazo scenaro: ili havis sekureco reguloj en loko por ĉiu pecon de teamo; funkcianta proceduroj por ĉiu ebla situacio; eventualeco planoj kiam aferoj iris malbone; kaj multnombraj aŭtomata kompensanta mekanismojn en tiu kazo la rezervo teamo ne funkcias. Ĉiuj el la industrio plej bonaj inĝenieroj laboradis diligente kaj konscience kun sekurecon kiel ilia alta prioritato. Tamen ankoraŭ io terura okazis. Kaj memoru, tio okazis 25 jarojn post Ĉernobilo, kun ampleksaj tempon por lerni el antaŭaj eraroj.</p>
			
			<p>Tiuj tagoj mi havas tre malfacile kredi preskaŭ ion ajn ke la nuklea energio kompanioj diru al mi. Malkara ol la alternativoj? Purigisto ol la alternativoj? Sekuraj ol la alternativoj? Ne. Ne. Ne.</p>
			
			<p><strong>Ĉiuj ĉi ĵus boli akvo?</strong></p>
	
			<p>Jen la simpla vero: estas nenio speciala pri elektro generitaj per nuklea energio. Oleo, karbo, gaso kaj nuklea ĉiuj uzas la saman mekanikon por generi elektron. Ĝi estas simpla:</p>
			
			<ol>
				<li>A varmego fonto bolas akvon.</li>
				<li>Vaporo el bolanta akvo fortoj turbino klingoj ŝpini.</li>
				<li>Indukto bobenoj alfiksita al la spinning turbino krei elektron kiam ĝi turnis per magneta kampo.</li>
			</ol>
			
			<p>Generante elektro estas nur elementa fiziko kaj inĝenierado. Do, kial iri al la problemoj de bolanta akvo per disigi atomoj? Kial krei danĝeran nuklea malŝparo, ke ni neniam povas forigi de? Kial ruinigu la medio kun uranio minado kaj molienda kiu kreas venena rubo-landoj? Kaj kial nuklea potenco firmaoj eksportas tiu danĝera teknologion al evoluantaj landoj?</p>
			
			<p>Do jen la peton. <strong>Ĉu vi povas helpi min por paroli pri tiuj simplaj faktoj?</strong> Mi ne petas vin aliĝi organizo aux donaci monon, sed simple aldoni vian nomon al la listo de kuraĝaj individuoj kiuj parolos favore mondo sen nukleaj fisio.</p>
			
			<p>Mi esperas ke ĉi tio faros diferencon.</p>
			
			<p>Joseph Honton<br />
			Sebastopol, California, USA</p>
ENDHTML;
	}
}
?>