<?php
//=============================================================================
//
// File:         /i18n/azLatnFavor.inc
//
// Language:     PHP
//
// Contents:     az-Latn = Azərbaycanca (Azerbaijani) using Google Translate
//
// Author:       Joe Honton © 2013
//
// Initial date: November 24, 2013
//
//=============================================================================

require_once( __DIR__ . '/azLatnBasePage.inc' );


//-------------------------------------
class azLatnFavor extends azLatnBasePage
{
	//---------------------------------
	function __construct( $language, $pagename )
	{
		parent::__construct( $language, $pagename );
	}
	
	//=============================================================================
	// Standard <head> items
	//=============================================================================
	
	//---------------------------------
	function pageTitle()
	{
		return "Mən bir tələbi var";
	}
	
	//---------------------------------
	function metaDescription()
	{
		return "Siz nüvə parçalanma təhlükələri haqqında cəsarətlə danışan kömək edə bilər.";
	}
	
	//---------------------------------
	function metaKeywords()
	{
		return "nüvə obyektləri, nüvə enerjisi, nüvə enerji, nüvə silahları, parçalanma, torpaq, qaynar su, elektrik";
	}
	
	//=============================================================================
	// Earth
	//=============================================================================
	
	//---------------------------------
	function blueMarble()
	{
		return "bizim gözəl mavi mərmər!";
	}
	
	//=============================================================================
	// Buttons
	//=============================================================================
	
	//---------------------------------
	function pledgeButton()
	{
		return "təntənəli söz";
	}
	
	//---------------------------------
	function pledgeButtonAlt()
	{
		return 'Indi "bir daha parçalanma" qalacağına and içməli!';
	}

	//=============================================================================
	// Content
	//=============================================================================
	
	//---------------------------------
	function content()
	{
return <<<ENDHTML
			<h1>Siz yüreklice danışan kömək edə bilər</h1>
			
			<p>Salam!</p>
			
			<p>Mən bir tələbi var. <strong>Siz nüvə parçalanma olmadan bu dünya etmək mənim axtarmaq mənə kömək edəcəkmi?</strong></p>
			
			<p>Mən bu barədə belə güclü hiss izah icazə.</p>
	
			<p>Mən böyüyən zaman, məkan kəşfiyyat tam şöhrət yüksəklikdə idi. Macəra müşayiət edən həyəcan hər kəs tərəfindən ortaq olmaq görünürdü. Hər yeni mərhələ müşayiət edən əsmək, daha çox us ac etdi. Və biz, həqiqətən ay bir adam qoymaq və yerdə təhlükəsiz ona qayıtmaq niyyətində olduğu gözləyiş, layihənin hətta kiçik uğurlar və uğursuzluqlar ilə məşğul bizi saxlanılır.</p>
			
			<p>Ki, son məqsədə nail olmaq əvvəl, bir çox əhəmiyyətli nailiyyətləri var idi. Astronavtların Yerin orbit pulsuz qırdı zaman bu ən maraqlı biri idi. İlk dəfə, insanlar öz ev planetin təhlükəsizliyini tərk edilmişdir. Biz bir ömür boyu macəra əsmək axtaran kimi idi.</p>
			
			<p>Və sonra ən gözəl şey oldu. Bu astronotlar süren Yerin geri saldı və ilk dəfə bizim ev idi ki, mavi mərmər gördüm, və onlar təxminən onlar zahir nə qiymətli gözəlliyi ilə böhrana düşən edilmişdir. Onlar geri göndərdi ki, foto şəkillər dünyaya yayımlanan edilmişdir və biz çox heyrətə salan idi.</p>
			
			<p>Bu fotoşəkillər tutulan açığı bütün siyasət transcended bir şəkildə özümüzü bizim şüurlu etdi. Vaxt qısa bir an üçün, biz fərqlər kənara, Soyuq Müharibə haqqında unuttum və biz Yerin gözəllik da heyrət. Bu yeni şüur biz kainatın yerimiz idi necə kövrək bilirdi, və yaxın biz heç olacaq yalnız ev məhv necə təhlükəli.</p>
			
			<p>Biz nöqsanların düzeltmek üçün yubanmadan ayıldım. Fəaliyyətinin bir partlayış ilə, biz problemləri həll etmək çalışmışdır. Nüvə silahların yayılmasının beynəlxalq müqavilə və nüvə silahlarının bütün yerüstü test qadağan müqavilə bizim ortaq dəyərləri haqqında danışmaq və ümumi həssas məqsədlərə nail əyani sübut idi. Nəhayət, Berlin Divarının yıxılmasından və Soyuq Müharibə əsas rəqibləri arasında əlaqələrin əriməsi ilə, biz nüvə silahlarının qlobal yığdığını azaldılmasına yönəldilmiş ilk ciddi səy başladı.</p>
			
			<p>Amma bu yana biz nüvə silahlarından azad bir dünya üçün şövq itirmiş, və ki, iş davam etmək üçün son səyləri çox real irəliləyiş yoxdur görünür. Sönük danışıqlar dörd onilliklər sonra, hətta işlər cari dövlət qadir olmamışdır:; yaşlanma qlobal ehtiyatları pisləşir; beynəlxalq nüvə müqavilələr circumvented və ya göz ardı edilmişdir və yeni nüvə silah araşdırma davam edir.</p>
			
			<p><strong>Önleme siyasəti aydın uğursuz oldu.</strong> Bizim ayıb, bu qeyri-müəyyən vədlər və boş ritorika ilə əvəz edilmişdir.</p>
			
			<p>Təəssüf ki, nüvə silahı bizim yalnız narahat deyil. Biz indi atom elektrik stansiyaları da bizim qiymətli Yerin üçün ciddi təhlükə yaradır ki, bilirik. Biz yalnız atom elektrik stansiyaları 100% təhlükəsiz edilə bilməz ki, həyata keçirilməsi üçün oyatmaq başlayır.</p>
			
			<p>Fukushima da fəlakət nüvə mühəndislər hər cür pis ssenariyə hazırlıqlı çünki baş olmalıdır ki, heç; hər cür vəziyyət üçün fəaliyyət prosedurları; zaman şeyi zaman yanlış hərəkət planları, onlar avadanlıqların hər parça üçün yer təhlükəsizlik qaydaları idi və halda çox avtomatik kompensasiya mexanizmləri ehtiyat avadanlıq işləmədi. Sənaye ən yaxşı mühəndisləri bütün prioritet kimi təhlükəsizlik ilə səylə və vicdanla işləyirlər. Hələ dəhşətli bir şey baş verib. Və unutmayın əvvəlki səhvləri öyrənmək üçün geniş vaxt, 25 il Çernobıl sonra meydana gəldi.</p>
			
			<p>Bu gün mən bir çox ağır vaxt nüvə enerji şirkətləri mənə demək olar ki, bir şey mö'min var. Alternativ daha ucuz? Alternativ daha təmiz? Alternativ daha etibarlı? Heç bir. Heç bir. Heç bir.</p>
			
			<p><strong>Bütün yalnız su qaynatmaq üçün?</strong></p>
	
			<p>Burada sadə həqiqət: nüvə elektrik stansiyalarının istehsal etdiyi elektrik enerjisinin haqqında xüsusi bir şey yoxdur. Neft, kömür, qaz və nüvə bütün elektrik yaradan üçün eyni mexanika istifadə edin. Çox sadə:</p>
			
			<ol>
				<li>A istilik mənbəyi su qaynayır.</li>
				<li>Fırlatmaq üçün qaynar su qüvvələr turbin bıçakları buxar.</li>
				<li>Bir maqnit sahəsi vasitəsilə qayıdacaqdır zaman dönüş turbin əlavə induksiya rulonlarda elektrik yaratmaq.</li>
			</ol>
			
			<p>Elektrik yaradan yalnız elementar fizika və mühəndislik edir. Belə ki, niyə atomları parçalanması qaynar su narahatlıq getmək? Niyə biz xilas heç vaxt bilər ki, təhlükəli nüvə tullantıları yaratmaq? Niyə zəhərli tullantılar-torpaqları yaradır uran mədən və freze ilə ətraf mühitə korlamaq? Və niyə inkişaf etməkdə olan ölkələr üçün bu təhlükəli texnologiya ixrac nüvə enerji şirkətləri var?</p>
			
			<p>Belə ki, burada tələb edir. <strong>Mənə bu faktları haqqında danışmaq üçün yardım edə bilərəmmi?</strong> Bir təşkilat qoşulmaq və ya pul bağış isteyen deyiləm, sadəcə nüvə parçalanma olmadan dünyanın lehinə çıxış edən cəsarətli şəxslərin siyahısı adınızı əlavə etmək.</p>
			
			<p>Mən bu fərq edəcək.</p>
			
			<p>Joseph Honton<br />
			Sebastopol, California, USA</p>
ENDHTML;
	}
}
?>