<?php
//=============================================================================
//
// File:         /i18n/msFavor.inc
//
// Language:     PHP
//
// Contents:     ms = Bahasa Melayu (Malay)
//
// Author:       Joe Honton © 2013
//
// Initial date: October 19, 2013
//
//=============================================================================

require_once( __DIR__ . '/msBasePage.inc' );


//-------------------------------------
class msFavor extends msBasePage
{
	//---------------------------------
	function __construct( $language, $pagename )
	{
		parent::__construct( $language, $pagename );
	}
	
	//=============================================================================
	// Standard <head> items
	//=============================================================================
	
	//---------------------------------
	function pageTitle()
	{
		return "Saya mempunyai permintaan";
	}
	
	//---------------------------------
	function metaDescription()
	{
		return "Anda boleh membantu dengan bercakap berani mengenai bahaya pembelahan nuklear.";
	}
	
	//---------------------------------
	function metaKeywords()
	{
		return "kemudahan nuklear, tenaga nuklear, senjata nuklear, pembelahan, Bumi, air panas, elektrik";
	}
	
	//=============================================================================
	// Earth
	//=============================================================================
	
	//---------------------------------
	function blueMarble()
	{
		return "marmar biru yang indah kami!";
	}
	
	//=============================================================================
	// Buttons
	//=============================================================================
	
	//---------------------------------
	function pledgeButton()
	{
		return "Sesungguhnya janji";
	}
	
	//---------------------------------
	function pledgeButtonAlt()
	{
		return 'Bersumpah "tidak lebih pembelahan" sumpah sekarang!';
	}

	//=============================================================================
	// Content		 
	//=============================================================================
	
	//---------------------------------
	function content()
	{
return <<<ENDHTML
			<h1>Anda boleh membantu dengan bercakap berani</h1>		 
			
			<p>Salam.</p>
			
			<p>Saya mempunyai permintaan. <strong>Anda akan membantu saya dalam usaha saya untuk membuat ini dunia tanpa pembelahan nuklear?</strong></p>
			
			<p>Izinkan saya untuk menjelaskan mengapa saya rasa begitu kuat tentang perkara ini.</p>
	
			<p>Apabila saya membesar, penerokaan angkasa adalah pada kemuncak kemuliaan sepenuhnya. Keseronokan yang disertai pengembaraan seolah-olah untuk dikongsi oleh semua orang. Keseronokan yang disertai setiap peristiwa baru, membangkitkan selera kami untuk lebih. Dan jangkaan yang kita benar-benar telah akan meletakkan seorang lelaki di bulan dan kembali dengan selamat ke Bumi, kami sentiasa terlibat dengan walaupun kejayaan kecil dan kegagalan projek.</p>
			
			<p>Sebelum mencapai matlamat utama, terdapat banyak pencapaian penting. Salah satu yang paling menyeronokkan ini adalah apabila angkasawan memecahkan bebas daripada orbit Bumi. Buat pertama kali, manusia telah meninggalkan keselamatan planet rumah mereka. Kami seperti pencari keseronokan di pengembaraan seumur hidup.</p>
			
			<p>Dan kemudian perkara yang paling luar biasa yang berlaku. Angkasawan menoleh kembali pada Bumi surut, dan melihat untuk pertama kalinya marmar biru yang berada di rumah kami, dan mereka hampir kewalahan dengan keindahan berharga daripada apa yang mereka melihat azab. Imej-imej fotografi yang mereka dihantar pulang telah disiarkan kepada dunia, dan kita juga tidak terpegun.</p>
			
			<p>Kelemahan orang-orang yang ditangkap di gambar menjadikan kita sedar diri kita sendiri dengan cara yang melampaui semua politik. Seketika ringkas dalam masa, kita lupa tentang Perang Dingin, kita mengetepikan perbezaan kita, dan kami kagum dengan keindahan Bumi. Dari kesedaran baru ini kita tahu betapa rapuh tempat kita di alam semesta adalah, dan bagaimana perilously dekat kita untuk memusnahkan satu-satunya rumah yang pernah kita akan mempunyai.</p>
			
			<p>Kami dikejutkan dengan rasa mendesak untuk menetapkan kelemahan kita. Dengan ledakan aktiviti, kita bekerja untuk menyelesaikan masalah kita. Perjanjian antarabangsa mengenai perkembangan senjata nuklear, dan perjanjian untuk mengharamkan semua ujian di atas tanah senjata nuklear adalah bukti bahawa kita boleh bercakap tentang nilai-nilai yang kita kongsi bersama dan mencapai matlamat wajar biasa. Akhirnya, dengan kejatuhan Tembok Berlin, dan pencairan hubungan antara pesaing utama Perang Dingin, kami memulakan usaha serius pertama bertujuan untuk mengurangkan stok simpanan global senjata nuklear.</p>
			
			<p>Tetapi oleh kerana masa itu kita seolah-olah telah kehilangan semangat kami untuk dunia yang bebas daripada senjata nuklear, dan usaha-usaha baru-baru ini untuk meneruskan kerja-kerja yang tidak membuat banyak kemajuan sebenar. Selepas empat dekad ceramah suram, kita telah tidak mampu untuk mengekalkan keadaan semasa hal ehwal: perjanjian nuklear antarabangsa telah dilepasi atau diabaikan; yang stok simpanan global penuaan yang semakin merosot; dan penyelidikan senjata nuklear baru terus.</p>
			
			<p><strong>Dasar pencegahan telah jelas gagal.</strong> Untuk memalukan kita, ia telah digantikan dengan janji-janji kabur dan retorik kosong.</p>
			
			<p>Malangnya, senjata nuklear tidak hanya kebimbangan kami. Kita kini tahu bahawa loji kuasa nuklear juga menimbulkan ancaman serius kepada Bumi berharga. Kami hanya mula menyedarkan kepada kesedaran bahawa loji kuasa nuklear tidak boleh dibuat 100% selamat.</p>
			
			<p>Malapetaka di Fukushima tidak sepatutnya berlaku kerana jurutera nuklear telah bersedia untuk setiap kemungkinan senario kes terburuk, mereka mempunyai peraturan-peraturan keselamatan di tempat untuk setiap sekeping peralatan; prosedur operasi bagi setiap keadaan yang mungkin; pelan kontingensi apabila perkara apabila salah dan pelbagai mekanisme pampasan automatik dalam kes peralatan rizab tidak berjaya. Semua jurutera terbaik industri telah bekerja bersungguh-sungguh dan kepercayaan dengan keselamatan sebagai keutamaan mereka. Namun masih sesuatu yang buruk berlaku. Dan ingat, ini berlaku 25 tahun selepas Chernobyl, dengan masa yang mencukupi untuk belajar dari kesilapan lalu.</p>
			
			<p>Hari ini saya mempunyai masa yang sangat sukar mempercayai hampir apa-apa yang syarikat-syarikat tenaga nuklear beritahu saya. Lebih murah daripada alternatif? Bersih daripada alternatif? Selamat daripada alternatif? Tidak. Tidak. Tidak.</p>
			
			<p><strong>Semua ini hanya mendidih air?</strong></p>
	
			<p>Berikut adalah kebenaran yang mudah: tiada apa yang istimewa tentang elektrik yang dijana oleh loji kuasa nuklear. Minyak, arang batu, gas, dan nuklear semua menggunakan mekanik yang sama untuk menjana elektrik. Ia adalah mudah:</p>
			
			<ol>
				<li>Satu sumber haba air mendidih.</li>
				<li>Wap dari air mendidih memaksa bilah turbin berputar.</li>
				<li>Gegelung induksi dilampirkan kepada turbin berputar mencipta elektrik apabila diputar melalui medan magnet.</li>
			</ol>
			
			<p>Menjana elektrik hanya fizik unsur dan kejuruteraan. Jadi mengapa pergi ke masalah air mendidih oleh atom pemisahan? Mengapa mewujudkan sisa nuklear yang berbahaya yang kita tidak boleh menghilangkan? Mengapa merosakkan alam sekitar dengan perlombongan uranium dan pengilangan yang menghasilkan sisa toksik-tanah? Dan mengapa syarikat kuasa nuklear mengeksport teknologi ini berbahaya kepada negara-negara membangun?</p>
			
			<p>Jadi di sini adalah permintaan. <strong>Bolehkah anda membantu saya untuk bercakap tentang fakta-fakta yang mudah?</strong> Saya tidak meminta anda untuk menyertai organisasi atau untuk menderma wang, tetapi semata-mata untuk menambah nama anda ke dalam senarai individu yang berani yang akan bercakap dalam memihak kepada dunia tanpa pembelahan nuklear.</p>
			
			<p>Saya harap ini akan membuat perbezaan.</p>
			
			<p>Joseph Honton<br />
			Sebastopol, California, USA</p>
ENDHTML;
	}
}
?>